openapi: 3.0.0

info:
  title: Syfo-MacGyver
  description: API for syfo-MacGyver. Husk å velge riktig url! :)
  version: 1.0.0
servers:
  - url: 'https://macgyver.dev.intern.nav.no'
  - url: 'https://macgyver.intern.nav.no'
paths:
  /api/sykmelding/fnr:
    post:
      operationId: endreBrukerFnr
      summary: Endre fnr for sykmeldinger
      description: Endrer fnr for et gitt fnr i alle sykmeldinger i SyfoSmRegister og oppdaterer aktive NL-koblinger
      tags:
        - Identendring
      security:
        - bearerAuth: [ ]
      requestBody:
        $ref: '#/components/requestBodies/EndreFnrRequest'
      responses:
        '200':
          description: Ok
        '304':
          description: Not Modified
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/leder/fnr:
    post:
      operationId: endreLederFnr
      summary: Endre fnr for nærmeste leder
      description: Oppdaterer aktive NL-koblinger for leder med nytt fnr
      tags:
        - Identendring
      security:
        - bearerAuth: [ ]
      requestBody:
        $ref: '#/components/requestBodies/EndreFnrRequest'
      responses:
        '200':
          description: Ok
        '304':
          description: Not Modified
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/sykmelding/{sykmeldingId}:
    delete:
      summary: Sletter en sykmelding
      operationId: deleteSykmelding
      tags:
        - Sykmelding
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /api/sykmelding/{sykmeldingId}/gjenapne:
    post:
      operationId: gjenapne
      tags:
        - Sykmelding
      security:
        - bearerAuth: [ ]
      summary: Gjenåpne sykmelding
      description: Gjenåpne sykmelding med gitt sykmeldingId
      parameters:
        - $ref: '#/components/parameters/sykmeldingId'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/oppgave/list:
    post:
      operationId: getOppgave
      tags:
        - Oppgave
      security:
        - bearerAuth: [ ]
      summary: Hent liste av oppgaver
      description: Hent en liste av oppgaver med oppgaveId fra Oppgave-api
      requestBody:
        $ref: '#/components/requestBodies/HentOppgaverRequest'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
  /api/narmesteleder/request:
    post:
      operationId: newNlRequest
      tags:
        - Narmesteleder
      security:
        - bearerAuth: [ ]
      description: Sender ny NL-request til altinn
      requestBody:
        $ref: '#/components/requestBodies/NlRequest'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

  /api/legeerklaering/{legeerklaeringId}:
    delete:
      summary: Sletter en legeerklaering
      operationId: deleteLegeerklaering
      tags:
        - Legeerklaering
      security:
        - bearerAuth: [ ]
      parameters:
        - $ref: '#/components/parameters/legeerklaeringId'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '500':
          description: InternalServerError
  /api/smregistrering/{journalpostId}/ferdigstill:
    post:
      operationId: ferdigstill
      tags:
        - Smregistrering
      security:
        - bearerAuth: [ ]
      summary: Ferdigstille registreringsoppgave
      description: Ferdigstille registreringsoppgave i Smregistrering og Oppgave (Gosys)
      parameters:
        - $ref: '#/components/parameters/journalpostId'
      requestBody:
        $ref: '#/components/requestBodies/FerdigstillSmregOppgaveRequest'
      responses:
        '200':
          description: Ok
        '401':
          description: Unauthorized
        '403':
          description: Forbidden

components:
  requestBodies:
    NlRequest:
      description: "Ny nl request"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NlRequest"
    EndreFnrRequest:
      description: "Endre fnr for bruker"
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/EndreFnr"
    HentOppgaverRequest:
      description: "Liste av oppgaveider som skal hentes"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/HentOppgaver'
    FerdigstillSmregOppgaveRequest:
      description: "Ident som skal brukes ved ferdigstilling av smreg-oppgave"
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FerdigstillSmregOppgave'

  parameters:
    sykmeldingId:
      description: Id for sykmelding som skal rettes
      name: sykmeldingId
      in: path
      required: true
      schema:
        type: string
      example: '123'
    journalpostId:
      description: Id for journalpost som skal ferdigstilles
      name: journalpostId
      in: path
      required: true
      schema:
        type: string
      example: '123'
    legeerklaeringId:
      description: Id for legeerklaering som skal rettes
      name: legeerklaeringId
      in: path
      required: true
      schema:
        type: string
      example: '83919f4d-f892-4db2-9255-f3c917bd012o'

  schemas:
    FerdigstillSmregOppgave:
      type: object
      required:
        - ferdigstiltAv
      properties:
        ferdigstiltAv:
          type: string
          minLength: 7
          maxLength: 7
          example: 'A123456'
    NlRequest:
      type: object
      required:
        - fnr
        - sykmeldingId
        - orgnummer
      properties:
        fnr:
          type: string
          minLength: 11
          maxLength: 11
        orgnummer:
          type: string
          minLength: 9
          maxLength: 9
        sykmeldingId:
          type: string
          format: uuid
    EndreFnr:
      type: object
      required:
        - fnr
        - nyttFnr
      properties:
        fnr:
          type: string
          minLength: 11
          maxLength: 11
        nyttFnr:
          type: string
          minLength: 11
          maxLength: 11
    HentOppgaver:
      type: array
      items:
        type: integer

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

security:
  - bearerAuth: [ ]
