apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: macgyver
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /api/internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /api/internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /api/internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 15m
      memory: 380Mi
  kafka:
    pool: nav-dev
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  accessPolicy:
    outbound:
      rules:
        - application: narmesteleder
        - application: syfosmregister
        - application: syfosmaltinn
        - application: syfosminfotrygd
      external:
        - host: saf.dev-fss-pub.nais.io
        - host: pdl-api.dev-fss-pub.nais.io
        - host: oppgave-q1.dev-fss-pub.nais.io
        - host: dokarkiv.dev-fss-pub.nais.io
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: trygdeetaten.no
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/*
        - /favicon.ico
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-syfosmregister-smregister-macgyver-38b6dc12
    - secret: macgyver-secrets
  ingresses:
    - "https://macgyver.intern.dev.nav.no"
  env:
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.dev-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://dev-fss.pdl.pdl-api/.default
    - name: KAFKA_CLIENT_ID
      value: macgyver
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave-q1.dev-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_SCOPE
      value: api://dev-fss.oppgavehandtering.oppgave-q1/.default
    - name: NARMESTELEDER_SCOPE
      value: api://dev-gcp.teamsykmelding.narmesteleder/.default
    - name: SYFOSMREGISTER_CLOUD_SQL_INSTANCE
      value: teamsykmelding-dev-1d34:europe-north1:smregister-instance
    - name: SYFOSMREGISTER_DB_NAME
      value: smregister
    - name: SAF_GRAPHQL_PATH
      value: https://saf.dev-fss-pub.nais.io/graphql
    - name: SAF_SCOPE
      value: api://dev-fss.teamdokumenthandtering.saf-q1/.default
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.dev-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://dev-fss.teamdokumenthandtering.dokarkiv-q1/.default
    - name: SYFOSMALTINN_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosmaltinn/.default
    - name: INFOTRYGD_SCOPE
      value: api://dev-gcp.teamsykmelding.syfosminfotrygd/.default
