apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: macgyver
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 2
    max: 3
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /internal/prometheus
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
  kafka:
    pool: nav-prod
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  accessPolicy:
    inbound:
      rules:
        - application: macgyver-frontend
          namespace: teamsykmelding
          cluster: prod-gcp
    outbound:
      rules:
        - application: macgyver-frontend
        - application: narmesteleder
        - application: syfosmregister
      external:
        - host: saf.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: oppgave.prod-fss-pub.nais.io
        - host: dokarkiv.prod-fss-pub.nais.io
  azure:
    application:
      allowAllUsers: true
      enabled: true
      tenant: nav.no
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-syfosmregister-smregister-macgyver-38b6dc12
    - secret: macgyver-secrets
    - secret: google-sql-smregistrering-backend-smregistrering-macgy-e6d883fe
  env:
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: KAFKA_CLIENT_ID
      value: macgyver
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default
    - name: NARMESTELEDER_SCOPE
      value: api://prod-gcp.teamsykmelding.narmesteleder/.default
    - name: SYFOSMREGISTER_CLOUD_SQL_INSTANCE
      value: teamsykmelding-prod-2acd:europe-north1:smregister-instance
    - name: SYFOSMREGISTER_DB_NAME
      value: smregister
    - name: SMREGISTRERING_CLOUD_SQL_INSTANCE
      value: teamsykmelding-prod-2acd:europe-north1:smregistrering-instance
    - name: SMREGISTRERING_DB_NAME
      value: smregistrering
    - name: SAF_GRAPHQL_PATH
      value: https://saf.prod-fss-pub.nais.io/graphql
    - name: SAF_SCOPE
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default