apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: macgyver
  namespace: teamsykmelding
  labels:
    team: teamsykmelding
spec:
  image: {{ image }}
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  port: 8080
  liveness:
    path: /api/internal/is_alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /api/internal/is_ready
    initialDelay: 30
    periodSeconds: 5
    timeout: 5
  prometheus:
    enabled: true
    path: /api/internal/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: loki
        - id: elastic
  resources:
    requests:
      cpu: 50m
      memory: 512Mi
  kafka:
    pool: nav-prod
  gcp:
    permissions:
      - resource:
          apiVersion: resourcemanager.cnrm.cloud.google.com/v1beta1
          kind: Project
        role: roles/cloudsql.client
  accessPolicy:
    outbound:
      rules:
        - application: narmesteleder
        - application: syfosmregister
        - application: syfosmaltinn
        - application: syfosminfotrygd
      external:
        - host: saf.prod-fss-pub.nais.io
        - host: pdl-api.prod-fss-pub.nais.io
        - host: oppgave.prod-fss-pub.nais.io
        - host: dokarkiv.prod-fss-pub.nais.io
  ingresses:
    - "https://macgyver.ansatt.nav.no"
  azure:
    application:
      enabled: true
      allowAllUsers: true
      tenant: nav.no
      claims:
        groups:
          - id: "3a541678-8965-45c4-844b-486a8b9b94a3"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /assets/*
        - /favicon.ico
  secureLogs:
    enabled: true
  envFrom:
    - secret: google-sql-syfosmregister-smregister-macgyver-38b6dc12
    - secret: macgyver-secrets
  env:
    - name: PDL_GRAPHQL_PATH
      value: https://pdl-api.prod-fss-pub.nais.io/graphql
    - name: PDL_SCOPE
      value: api://prod-fss.pdl.pdl-api/.default
    - name: KAFKA_CLIENT_ID
      value: macgyver
    - name: OPPGAVEBEHANDLING_URL
      value: https://oppgave.prod-fss-pub.nais.io/api/v1/oppgaver
    - name: OPPGAVE_SCOPE
      value: api://prod-fss.oppgavehandtering.oppgave/.default
    - name: NARMESTELEDER_SCOPE
      value: api://prod-gcp.teamsykmelding.narmesteleder/.default
    - name: SYFOSMREGISTER_CLOUD_SQL_INSTANCE
      value: teamsykmelding-prod-2acd:europe-north1:smregister-instance
    - name: SYFOSMREGISTER_DB_NAME
      value: smregister
    - name: SAF_GRAPHQL_PATH
      value: https://saf.prod-fss-pub.nais.io/graphql
    - name: SAF_SCOPE
      value: api://prod-fss.teamdokumenthandtering.saf/.default
    - name: DOK_ARKIV_URL
      value: https://dokarkiv.prod-fss-pub.nais.io/rest/journalpostapi/v1/journalpost
    - name: DOK_ARKIV_SCOPE
      value: api://prod-fss.teamdokumenthandtering.dokarkiv/.default
    - name: SYFOSMALTINN_SCOPE
      value: api://prod-gcp.teamsykmelding.syfosmaltinn/.default
    - name: INFOTRYGD_SCOPE
      value: api://prod-gcp.teamsykmelding.syfosminfotrygd/.default
